---
- hosts: all
  sudo: yes
  roles:
    - common
    - kubernetes

- hosts: etcd
  sudo: yes
  roles:
    - etcd

- hosts: etcd_flannel
  sudo: yes
  roles:
    - etcd_flannel

- hosts: masters
  sudo: yes
  roles:
    - master

- hosts: minions
  sudo: yes
  roles:
    - minion

- hosts: masters
  sudo: yes
  roles:
    - flannel-master

- hosts: minions
  sudo: yes
  roles:
    - flannel-minion
