---
- hosts: all
  sudo: yes
  roles:
    - common
    - kubernetes

- hosts: etcd
  sudo: yes
  roles:
    - etcd

- hosts: masters
  sudo: yes
  roles:
    - master

- hosts: minions
  sudo: yes
  roles:
    - minion
